#!/bin/sh

# Formatting output
BOLD=$(tput bold)
REGULAR=$(tput sgr0)

BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
NOCOLOR='\033[0m'

workingdir="$(pwd)"
tempdir="/tmp/temprepo-$(date | awk '{print $5}' | sed 's/:/-/g')"
mkdir -p $tempdir
cd $tempdir

gitmakeinstall() {
    gitrepo="$(echo $1 | sed -e 's/^.*\///' -e 's/\.git$//')"
    git clone $1 $tempdir/$gitrepo
    cd $tempdir/$gitrepo
    sudo make clean install
    cd $tempdir
}

debinstall() {
    cd $tempdir
    deb="$(echo $1 | sed 's/.*\///g')"
    wget $1
    sudo apt install -f $(readlink -f $deb)
}

sudo apt install -f &&
    sudo apt update &&
    sudo apt upgrade

while IFS="," read -r source package comment
do
    printf "\n"
    printf "${BLUE}${BOLD}$package: ${YELLOW}${BOLD}$comment${NOCOLOR}\n"
    printf "\n"

    case $source in
        APT)
            sudo apt install -y $package
            ;;
        DEB)
            debinstall $package
            ;;
        GIT)
            gitmakeinstall $package
            ;;
        *)
            printf "Source for $package not recognized!\n"
            ;;
    esac
done < "$workingdir/package.list"

path="$workingdir/dotfiles"
cd $workingdir

files="$(find dotfiles -mindepth 1 -type f | sed 's/[^/]*\///')"
dirs="$(find dotfiles -mindepth 1 -type d | sed 's/[^/]*\///')"

for dir in $dirs; do
    mkdir -p $HOME/$dir
done

for file in $files; do
    ln -sf "$path/$file" "$HOME/$file"
done

sudo apt autoremove

rm -rf $tempdir
